<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Browserversion;

/**
 * BrowserversionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BrowserversionRepository extends EntityRepository
{
    /**
     * Add BrowserVersion to DB
     * @param Browserversion $browser
     * @throws \Exception
     */
    public function addBrowserversion(Browserversion $browser)
    {
        // Check for doubles
        $double = $this->findOneBy([
            'browser' => $browser->getBrowser(),
            'version' => $browser->getVersion()
        ]);

        if ($double instanceof Browserversion) {
            throw new \Exception('Browserversion with such parameters already presents in DB');
        }
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }

    /**
     * Remove BrowserVersion from DB
     *
     * @param Browserversion $browser
     * @throws \Exception
     */
    public function removeBrowserversion(Browserversion $browser)
    {
        try {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($browser);
            $entityManager->flush();
        } catch (ForeignKeyConstraintViolationException $e ) {
            throw new \Exception('Can\'t delete, because probably you have foreign key restrictions');
        }
    }

    /**
     * Modify browser version record in DB
     *
     * @param Browserversion $browser
     */
    public function modifyBrowserversion(Browserversion $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }    
}
