<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Browser;
use Doctrine\ORM\EntityRepository;

/**
 * BrowserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BrowserRepository extends EntityRepository
{
    public function addBrowser(Browser $browser)
    {
        $double = $this->findOneByName($browser->getName());
        if ($double instanceof Browser) {
            throw new \Exception('Browser with such name already presents in DB');
        }

        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }

    public function removeBrowser(Browser $browser)
    {
        try {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($browser);
            $entityManager->flush();
        } catch (ForeignKeyConstraintViolationException $e ) {
            throw new \Exception('Can\'t delete, because probably you have foreign key restrictions');
        }
    }

    public function modifyBrowser(Browser $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }
}
