<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Browserversion;

/**
 * BrowserversionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BrowserversionRepository extends EntityRepository
{
    public function addBrowserversion(Browserversion $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }

    public function removeBrowserversion(Browserversion $browser)
    {
        try {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($browser);
            $entityManager->flush();
        } catch (ForeignKeyConstraintViolationException $e ) {
            throw new \Exception('Can\'t delete, because probably you have foreign key restrictions');
        }
    }

    public function modifyBrowserversion(Browserversion $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }    
}
