<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\DeviceBrowser;
/**
 * DeviceBrowserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DeviceBrowserRepository extends EntityRepository
{
    public function addDeviceBrowser(DeviceBrowser $browser)
    {
        $double = $this->findOneBy([
            'device' => $browser->getDevice(),
            'browserversion' => $browser->getBrowserversion()
        ]);
        if ($double instanceof DeviceBrowser) {
            throw new \Exception('DeviceBrowser with such parameters already presents in DB');
        }
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }

    public function removeDeviceBrowser(DeviceBrowser $browser)
    {
        try {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($browser);
            $entityManager->flush();
        } catch (ForeignKeyConstraintViolationException $e ) {
            throw new \Exception('Can\'t delete, because probably you have foreign key restrictions');
        }
    }

    public function modifyDeviceBrowser(DeviceBrowser $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }
}
