<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Device;
use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    public function addDevice(Device $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }

    public function removeDevice(Device $browser)
    {
        try {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($browser);
            $entityManager->flush();
        } catch (ForeignKeyConstraintViolationException $e ) {
            throw new \Exception('Can\'t delete, because probably you have foreign key restrictions');
        }
    }

    public function modifyDevice(Device $browser)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($browser);
        $entityManager->flush();
    }
}
