# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.service.browser:
    class: 'AppBundle\Service\RepositoryService'
    arguments: ["@=service('doctrine').getRepository('AppBundle:Browser')"]
  app.service.device:
    class: 'AppBundle\Service\RepositoryService'
    arguments: ["@=service('doctrine').getRepository('AppBundle:Device')"]
  app.service.devicebrowser:
    class: 'AppBundle\Service\RepositoryService'
    arguments: ["@=service('doctrine').getRepository('AppBundle:DeviceBrowser')"]
  app.service.browserversion:
    class: 'AppBundle\Service\RepositoryService'
    arguments: ["@=service('doctrine').getRepository('AppBundle:Browserversion')"]
  app.service.devicetype:
    class: 'AppBundle\Service\RepositoryService'
    arguments: ["@=service('doctrine').getRepository('AppBundle:Devicetypes')"]
