device:
    type: rest
    prefix: /v1
    resource: AppBundle:Device
    name_prefix:  api_v1_

devicebrowser:
    type: rest
    prefix: /v1
    resource: AppBundle:DeviceBrowser
    name_prefix:  api_v1_

browser:
    type: rest
    prefix: /v1
    resource: AppBundle:Browser
    name_prefix:  api_v1_

browserversion:
    type: rest
    prefix: /v1
    resource: AppBundle:BrowserVersion
    name_prefix:  api_v1_